version: '3.9'

services:

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    env_file:
      - .env

  web:
    build: .
    # command: gunicorn Carttart.wsgi:application --bind 0.0.0.0:8000
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn Carttart.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"  # Exposing port 8000 for web access
    env_file:
      - .env
