version: '3.9'

services:
  carttart:
    build: 
      context: .
      dockerfile: dockerfile.prod  # Use Dockerfile.prod or Dockerfile.dev based on ENV
    # command: gunicorn Carttart.wsgi:application --bind 0.0.0.0:8000
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn Carttart.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:80"  # Exposing port 8000 for web access
    env_file:
      - .env

 