# Generated by Django 5.1.4 on 2025-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('commerce', 'commerce'), ('energy', 'energy'), ('esports', 'esports'), ('fintech', 'fintech'), ('healthcare', 'healthcare'), ('realestate', 'realestate')], default='readerclub', max_length=20),
        ),
    ]
