# Generated by Django 5.1.5 on 2025-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_image_alter_blog_blog_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('commerce', 'commerce'), ('energy', 'energy'), ('esports', 'esports'), ('fintech', 'fintech'), ('healthcare', 'healthcare'), ('realestate', 'realestate')], default='healthcare', max_length=20),
        ),
    ]
