# Generated by Django 5.1.4 on 2025-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('commerce', 'commerce'), ('energy', 'energy'), ('esports', 'esports'), ('fintech', 'fintech'), ('healthcare', 'healthcare'), ('realestate', 'realestate'), ('tour', 'tour')], default='healthcare', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
