# Generated by Django 5.1.5 on 2025-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('sector', models.CharField(choices=[('healthcare', 'Healthcare'), ('fintech', 'Fintech'), ('realestate', 'Real Estate'), ('ecommerce', 'E-commerce'), ('esports', 'Esports'), ('tourism', 'Tourism'), ('energy', 'Energy')], default='other', max_length=50)),
            ],
        ),
    ]
