# Generated by Django 5.1.5 on 2025-04-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientlogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlogo',
            name='name',
        ),
    ]
